<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Vladyslav Zaiets</Authors>
    <PackageProjectUrl>https://github.com/sarmkadan/telegram-bot-framework-dotnet</PackageProjectUrl>
  </PropertyGroup>
</Project>