// tests/TelegramBotFramework.Tests/Models/TelegramBotFrameworkDotnetOptionsExtensionsTestsExtensions.cs
// 
// Created by [Your Name] on [Date]
// 
// This file was generated by [Your Assistant] on [Date]

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using TelegramBotFramework.Tests.Models;

/// <summary>
/// Extensions for the TelegramBotFrameworkDotnetOptionsExtensionsTests class.
/// </summary>
public static class TelegramBotFrameworkDotnetOptionsExtensionsTestsExtensions
{
    /// <summary>
    /// Validates that the options are valid without throwing an exception.
    /// </summary>
    /// <param name="tests">The tests instance.</param>
    /// <param name="customMessage">The custom message to use.</param>
    public static void Validate_OptionsAreValid_DoesNotThrowWithCustomMessage(this TelegramBotFrameworkDotnetOptionsExtensionsTests tests, string customMessage)
    {
        ArgumentNullException.ThrowIfNull(tests);
        ArgumentNullException.ThrowIfNull(customMessage);

        tests.Validate_OptionsAreValid_DoesNotThrow();
        tests.Options = new TelegramBotFrameworkDotnetOptions { SessionTimeout = TimeSpan.FromHours(1), MessageProcessingTimeout = TimeSpan.FromMinutes(5), DatabaseConnectionString = "Custom Connection String" };
        tests.Validate_OptionsAreValid_DoesNotThrow();
    }

    /// <summary>
    /// Validates that the options are invalid and throws an InvalidOperationException.
    /// </summary>
    /// <param name="tests">The tests instance.</param>
    /// <param name="customMessage">The custom message to use.</param>
    public static void Validate_OptionsAreInvalid_ThrowsInvalidOperationExceptionWithCustomMessage(this TelegramBotFrameworkDotnetOptionsExtensionsTests tests, string customMessage)
    {
        ArgumentNullException.ThrowIfNull(tests);
        ArgumentNullException.ThrowIfNull(customMessage);

        tests.Options = new TelegramBotFrameworkDotnetOptions { SessionTimeout = TimeSpan.FromHours(1), MessageProcessingTimeout = TimeSpan.FromMinutes(5) };
        tests.Validate_OptionsAreInvalid_ThrowsInvalidOperationException();
    }

    /// <summary>
    /// Gets the session timeout from the options.
    /// </summary>
    /// <param name="tests">The tests instance.</param>
    /// <param name="culture">The culture to use.</param>
    public static void GetSessionTimeout_OptionsHaveSessionTimeout_ReturnsTimeSpanWithCustomCulture(this TelegramBotFrameworkDotnetOptionsExtensionsTests tests, CultureInfo culture)
    {
        ArgumentNullException.ThrowIfNull(tests);
        ArgumentNullException.ThrowIfNull(culture);

        tests.Options = new TelegramBotFrameworkDotnetOptions { SessionTimeout = TimeSpan.FromHours(1), MessageProcessingTimeout = TimeSpan.FromMinutes(5), DatabaseConnectionString = "Custom Connection String" };
        tests.GetSessionTimeout_OptionsHaveSessionTimeout_ReturnsTimeSpan();
    }

    /// <summary>
    /// Gets the message processing timeout from the options.
    /// </summary>
    /// <param name="tests">The tests instance.</param>
    /// <param name="culture">The culture to use.</param>
    public static void GetMessageProcessingTimeout_OptionsHaveMessageProcessingTimeout_ReturnsTimeSpanWithCustomCulture(this TelegramBotFrameworkDotnetOptionsExtensionsTests tests, CultureInfo culture)
    {
        ArgumentNullException.ThrowIfNull(tests);
        ArgumentNullException.ThrowIfNull(culture);

        tests.Options = new TelegramBotFrameworkDotnetOptions { SessionTimeout = TimeSpan.FromHours(1), MessageProcessingTimeout = TimeSpan.FromMinutes(5), DatabaseConnectionString = "Custom Connection String" };
        tests.GetMessageProcessingTimeout_OptionsHaveMessageProcessingTimeout_ReturnsTimeSpan();
    }
}
